# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Client(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Client()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClient(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Client
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Client
    def Person(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Person import Person
            obj = Person()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Client
    def Group(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Group import Group
            obj = Group()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Client
    def IsPerson(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(3)
def ClientStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddPerson(builder, person): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(person), 0)
def ClientAddPerson(builder, person):
    """This method is deprecated. Please switch to AddPerson."""
    return AddPerson(builder, person)
def AddGroup(builder, group): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(group), 0)
def ClientAddGroup(builder, group):
    """This method is deprecated. Please switch to AddGroup."""
    return AddGroup(builder, group)
def AddIsPerson(builder, isPerson): builder.PrependBoolSlot(2, isPerson, 0)
def ClientAddIsPerson(builder, isPerson):
    """This method is deprecated. Please switch to AddIsPerson."""
    return AddIsPerson(builder, isPerson)
def End(builder): return builder.EndObject()
def ClientEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)