# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClientList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClientList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClientList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClientList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClientList
    def Clients(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Client import Client
            obj = Client()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ClientList
    def ClientsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ClientList
    def ClientsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def ClientListStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddClients(builder, clients): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clients), 0)
def ClientListAddClients(builder, clients):
    """This method is deprecated. Please switch to AddClients."""
    return AddClients(builder, clients)
def StartClientsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ClientListStartClientsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartClientsVector(builder, numElems)
def End(builder): return builder.EndObject()
def ClientListEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)